apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: tailscale-dns
  name: coredns
  namespace: tailscale
data:
  Corefile: |
    .:53 {
        errors
        health {
           lameduck 5s
        }
        ready
        template IN A arata.internal {
            match ^.*\.arata\.internal\.$
            answer "{{ .Name }} 60 IN A TODO"
            fallthrough
        }
        forward . 10.96.0.10
        log
    }
