apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: metrics-server
    releaseName: metrics-server
    namespace: metrics-server
    version: 3.12.1
    repo: https://kubernetes-sigs.github.io/metrics-server/
    valuesFile: values.yaml

resources:
  - namespace.yaml
