apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: headlamp
    releaseName: headlamp
    namespace: headlamp
    version: 0.38.0
    repo: https://kubernetes-sigs.github.io/headlamp/

resources:
  - ingressroute.yaml
  - namespace.yaml
