apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: argo-cd
    releaseName: argocd
    namespace: argocd
    version: 9.1.0
    repo: https://argoproj.github.io/argo-helm
    valuesFile: values.yaml

resources:
  - ingressroute.yaml
  - namespace.yaml

patches:
  - path: argocd-cm.yaml
