apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/arata-nvm/utou-infra
    targetRevision: main
    path: kubernetes/tailscale
  destination:
    namespace: tailscale
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}
